#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json | awk '{printf "%.0fkg", $1/10}')
height=$(jq -r '.height' data.json | awk '{printf "%.1fm", $1/10}')

echo "$name is of type $type, weighs $weight, and is $height tall."
